level1 = [
    "PPPPPPPPPPPPPPPPPPPP",
    "P            U     P",
    "P                  P",
    "P     0            P",
    "P     U            P",
    "P   PPP            P",
    "PUUUUUUUUUUUU      P",
    "P     UUUUUUUUU    P",
    "P     0UUUUUUUU1   P",
    "PPPPPPPPPPPPPPPP   P",
    "P                  P",
    "P           WWWWWWWP",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "PA                 P",
    "PA                 P",
    "PA                 P",
    "PA                 P",
    "PA       MS        P",
    "P                  P",
    "P               U  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "PAAAAAAASSSSAAAAAAAP",
    "P                  P",
    "P                  P",
    "P                  P",
    "P      AAAAAA      P",
    "P                  P",
    "P     A            P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P        U         P",
    "P              S   P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P           A      P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P S                P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P        A         P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P                  P",
    "P1             AAAAP",
    "P                  P",
    "P                  P",
    "P         A        P",
    "P   U   AAAAAA    EP",
    "PPPPPPPPPPPPPPPPPPPP"]

level2 = [  "PPPPPPPPPPPPPPPPPPPP",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "PPPPPPPP  AAAAAAAAAP",
            "P       S          P",
            "P       S          P",
            "P       S          P",
            "P       A          P",
            "P       S          P",
            "P       S          P",
            "P       S          P",
            "P       S          P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P     A            P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P        U         P",
            "P              S   P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P           A      P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P S                P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P        A         P",
            "P                ASP",
            "P               A SP",
            "P              A  SP",
            "P             A   SP",
            "P            A     P",
            "P           A      P",
            "P          A       P",
            "P         A        P",
            "P        A         P",
            "P       A          P",
            "P      A           P",
            "P     A            P",
            "P    A             P",
            "P   A              P",
            "P  A               P",
            "P A                P",
            "PA                 P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                 AP",
            "P                A P",
            "P               A  P",
            "P              A   P",
            "P             A    P",
            "P            A     P",
            "P           A      P",
            "P          A       P",
            "P         A        P",
            "P        A         P",
            "P       A          P",
            "P      A           P",
            "P     A            P",
            "P    A             P",
            "P   A              P",
            "P  A               P",
            "P A                P",
            "P                  P",
            "P                  P",
            "P                  P",
            "PPPPAAAAAAAAAAAAAA P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P              AAAAP",
            "P                  P",
            "P                  P",
            "P   U     U       EP",
            "PPPPPPPPPPPPPPPPPPPP"]
level3 = ["PPPPPPPPPPPPPPPPPPPP",
            "P                  P",
            "P                 PP",
            "P                  P",
            "PPPPP              P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "P                  P",
            "PAAAAAAAAAAAAAAAA AP",
            "P                  P",
            "P                 EP",
            "PPPPPPPPPPPPPPPPPPPP"]

infinite_start = ["PPPPPPPPPPPPPPPPPPPP",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P",
                    "P                  P"]
